name: .NET Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/packages.lock.json"
      - "Directory.*.props"
      - "global.json"
      - "Split.slnx"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/packages.lock.json"
      - "Directory.*.props"
      - "global.json"
      - "Split.slnx"

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
