name: NPM Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Application/Frontend/**"
      - ".github/workflows/npm-tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Application/Frontend/**"
      - ".github/workflows/npm-tests.yml"

jobs:
  check-and-lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "24.4.1"

      - name: Install dependencies
        run: npm ci
        working-directory: Application/Frontend

      - name: Svelte check
        run: npm run check
        working-directory: ./Application/Frontend

      - name: Run linter
        run: npm run lint
        working-directory: ./Application/Frontend
